package com.example.localguidebe.enums;

public enum NotificationTypeEnum {
  CANCEL_TOUR,
  CONFIRM_TOUR_BOOKING,
  TOUR_REVIEW,
  REMINDER,
  ADD_REVIEW_FOR_GUIDE,
  ADD_REVIEW_FOR_TOUR,
  ADD_TOUR,
  BOOKED_TOUR,
  RECEIVED_BOOKING,
  ACCEPTED_TOUR,
  DENY_TOUR
}
